"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ArticleTypeInfoTypedDict(TypedDict):
    r"""Success"""

    article_category_id: NotRequired[int]
    r"""Specifies the article category ID."""
    type_name: NotRequired[str]
    r"""Indicates the article type name."""
    use_structured_authoring: NotRequired[bool]
    r"""Indicates whether structured authoring is enabled for this article type, requiring content to be created using predefined fields"""
    article_type_id: NotRequired[str]
    r"""The ID of the Article Type."""
    image_url: NotRequired[str]
    r"""The URL of an image to be associated with the Article Type"""
    description: NotRequired[str]
    r"""Description of Article Type"""
    is_searchable: NotRequired[bool]
    r"""Indicates whether articles of this type are included in portal search results"""
    is_browsable: NotRequired[bool]
    r"""Indicates whether articles of this type are displayed in portal browsing areas such as topics and lists"""


class ArticleTypeInfo(BaseModel):
    r"""Success"""

    article_category_id: Annotated[
        Optional[int], pydantic.Field(alias="articleCategoryId")
    ] = None
    r"""Specifies the article category ID."""

    type_name: Annotated[Optional[str], pydantic.Field(alias="typeName")] = None
    r"""Indicates the article type name."""

    use_structured_authoring: Annotated[
        Optional[bool], pydantic.Field(alias="useStructuredAuthoring")
    ] = None
    r"""Indicates whether structured authoring is enabled for this article type, requiring content to be created using predefined fields"""

    article_type_id: Annotated[Optional[str], pydantic.Field(alias="articleTypeId")] = (
        None
    )
    r"""The ID of the Article Type."""

    image_url: Annotated[Optional[str], pydantic.Field(alias="imageURL")] = None
    r"""The URL of an image to be associated with the Article Type"""

    description: Optional[str] = None
    r"""Description of Article Type"""

    is_searchable: Annotated[Optional[bool], pydantic.Field(alias="isSearchable")] = (
        None
    )
    r"""Indicates whether articles of this type are included in portal search results"""

    is_browsable: Annotated[Optional[bool], pydantic.Field(alias="isBrowsable")] = None
    r"""Indicates whether articles of this type are displayed in portal browsing areas such as topics and lists"""
