"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ArticleActivityLinkCode = Literal[
    "en-US",
    "fr-FR",
    "en-GB",
    "es-ES",
    "it-IT",
    "nl-NL",
    "da-DA",
    "sv-SE",
    "pt-PT",
    "fi-FI",
    "no-NB",
    "no-NN",
    "ja-JA",
    "de-DE",
    "pt-BR",
    "zh-CN",
    "zh-TW",
    "ko-KO",
    "ru-RU",
    "el-EL",
    "tr-TR",
    "pl-PL",
    "cs-CS",
    "sk-SK",
    "hu-HU",
    "sr-SR",
    "ar-SA",
    "hr-HR",
    "ro-RO",
    "th-TH",
    "de-AT",
    "vi-VN",
    "id-ID",
    "ms-MY",
    "fil-PH",
    "fr-CA",
    "hi-IN",
    "uk-UA",
    "bg-BG",
    "sl-SI",
    "xx-XX",
]
r"""The code of the language."""


class ArticleActivityLinkLanguageTypedDict(TypedDict):
    r"""The knowledge base language in which the version is created."""

    code: ArticleActivityLinkCode
    r"""The code of the language."""


class ArticleActivityLinkLanguage(BaseModel):
    r"""The knowledge base language in which the version is created."""

    code: ArticleActivityLinkCode
    r"""The code of the language."""


class ArticleActivityLinkTypedDict(TypedDict):
    version_id: str
    r"""An Article version's ID."""
    language: ArticleActivityLinkLanguageTypedDict
    r"""The knowledge base language in which the version is created."""
    edition_id: NotRequired[str]
    r"""An Article edition's ID."""


class ArticleActivityLink(BaseModel):
    version_id: Annotated[str, pydantic.Field(alias="versionId")]
    r"""An Article version's ID."""

    language: ArticleActivityLinkLanguage
    r"""The knowledge base language in which the version is created."""

    edition_id: Annotated[Optional[str], pydantic.Field(alias="editionId")] = None
    r"""An Article edition's ID."""
