"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .folderbreadcrumb import FolderBreadcrumb, FolderBreadcrumbTypedDict
from egain_api_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BookmarkStatusTypedDict(TypedDict):
    r"""Article Bookmark Status"""

    is_bookmarked: bool
    r"""Indicates whether the Article is bookmarked"""
    bookmark_id: NotRequired[Nullable[int]]
    r"""The ID of the Bookmark, if Article is bookmarked."""
    folder_breadcrumb: NotRequired[FolderBreadcrumbTypedDict]
    r"""This schema contains one or more FolderSummary instances."""


class BookmarkStatus(BaseModel):
    r"""Article Bookmark Status"""

    is_bookmarked: Annotated[bool, pydantic.Field(alias="isBookmarked")]
    r"""Indicates whether the Article is bookmarked"""

    bookmark_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="bookmarkID")
    ] = UNSET
    r"""The ID of the Bookmark, if Article is bookmarked."""

    folder_breadcrumb: Annotated[
        Optional[FolderBreadcrumb], pydantic.Field(alias="folderBreadcrumb")
    ] = None
    r"""This schema contains one or more FolderSummary instances."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["bookmarkID", "folderBreadcrumb"]
        nullable_fields = ["bookmarkID"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
