"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateCommentTypedDict(TypedDict):
    r"""This schema contains the definition for comment creation."""

    content: NotRequired[str]
    r"""Content of the Comment"""


class CreateComment(BaseModel):
    r"""This schema contains the definition for comment creation."""

    content: Optional[str] = None
    r"""Content of the Comment"""
