"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fileobject import FileObject, FileObjectTypedDict
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


CREATE_VALIDATION_HOOK_VERSION_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
]


class CreateValidationHookVersionRequestTypedDict(TypedDict):
    hook_id: int
    r"""Integer ID of the Hook resource."""
    file_object: FileObjectTypedDict


class CreateValidationHookVersionRequest(BaseModel):
    hook_id: Annotated[
        int,
        pydantic.Field(alias="hookID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Integer ID of the Hook resource."""

    file_object: Annotated[
        FileObject,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
