"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DataSourceCredentialsTypedDict(TypedDict):
    access_key: NotRequired[str]
    r"""Access key for S3 credentials datasource. Provide along with Secret Key."""
    secret_key: NotRequired[str]
    r"""Secret key for S3 credentials datasource. Provide along with Access Key."""
    username: NotRequired[str]
    r"""Username for SFTP credentials datasource. Provide along with Password."""
    password: NotRequired[str]
    r"""Password for SFTP credentials datasource. Provide along with Username."""


class DataSourceCredentials(BaseModel):
    access_key: Annotated[Optional[str], pydantic.Field(alias="accessKey")] = None
    r"""Access key for S3 credentials datasource. Provide along with Secret Key."""

    secret_key: Annotated[Optional[str], pydantic.Field(alias="secretKey")] = None
    r"""Secret key for S3 credentials datasource. Provide along with Access Key."""

    username: Optional[str] = None
    r"""Username for SFTP credentials datasource. Provide along with Password."""

    password: Optional[str] = None
    r"""Password for SFTP credentials datasource. Provide along with Username."""
