"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ExecutePromptResponseEventType = Literal[
    "generate",
    "regenerate",
]


SessionStatus = Literal[
    "active",
    "inactive",
]


EventRegistration = Literal[
    "successful",
    "unsuccessful",
]


class ExecutePromptResponseTypedDict(TypedDict):
    generated_response: str
    r"""Final response from the LLM. If streaming is enabled, this contains a streaming link."""
    event_type: ExecutePromptResponseEventType
    session_id: str
    session_status: SessionStatus
    event_registration: EventRegistration
    client_session_id: NotRequired[str]
    r"""Client provided sessionID to store events against."""


class ExecutePromptResponse(BaseModel):
    generated_response: Annotated[str, pydantic.Field(alias="generatedResponse")]
    r"""Final response from the LLM. If streaming is enabled, this contains a streaming link."""

    event_type: Annotated[
        ExecutePromptResponseEventType, pydantic.Field(alias="eventType")
    ]

    session_id: Annotated[str, pydantic.Field(alias="sessionId")]

    session_status: Annotated[SessionStatus, pydantic.Field(alias="sessionStatus")]

    event_registration: Annotated[
        EventRegistration, pydantic.Field(alias="eventRegistration")
    ]

    client_session_id: Annotated[
        Optional[str], pydantic.Field(alias="clientSessionId")
    ] = None
    r"""Client provided sessionID to store events against."""
