"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .replacement import Replacement, ReplacementTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


LanguageCodeRequestBody = Literal[
    "en-US",
    "fr-FR",
    "en-GB",
    "es-ES",
    "it-IT",
    "nl-NL",
    "da-DA",
    "sv-SE",
    "pt-PT",
    "fi-FI",
    "no-NB",
    "no-NN",
    "ja-JA",
    "de-DE",
    "pt-BR",
    "zh-CN",
    "zh-TW",
    "ko-KO",
    "ru-RU",
    "el-EL",
    "tr-TR",
    "pl-PL",
    "cs-CS",
    "sk-SK",
    "hu-HU",
    "sr-SR",
    "ar-SA",
    "hr-HR",
    "ro-RO",
    "th-TH",
    "xx-XX",
]
r"""The language used for the prompt template."""


EventTypeRequestBody = Literal[
    "generate",
    "regenerate",
]
r"""Event type logged when the API executes successfully."""


class ExecutePromptTypedDict(TypedDict):
    department: str
    r"""Name of the department. Must be a valid department name."""
    language_code: LanguageCodeRequestBody
    r"""The language used for the prompt template."""
    replacements: NotRequired[List[ReplacementTypedDict]]
    r"""List of variable replacements (either static or search)."""
    event_type: NotRequired[EventTypeRequestBody]
    r"""Event type logged when the API executes successfully."""
    client_session_id: NotRequired[str]
    r"""Client provided sessionID to store events against."""
    streaming: NotRequired[bool]
    r"""Whether to stream the response instead of returning inline."""


class ExecutePrompt(BaseModel):
    department: str
    r"""Name of the department. Must be a valid department name."""

    language_code: Annotated[
        LanguageCodeRequestBody, pydantic.Field(alias="languageCode")
    ]
    r"""The language used for the prompt template."""

    replacements: Optional[List[Replacement]] = None
    r"""List of variable replacements (either static or search)."""

    event_type: Annotated[
        Optional[EventTypeRequestBody], pydantic.Field(alias="eventType")
    ] = "generate"
    r"""Event type logged when the API executes successfully."""

    client_session_id: Annotated[
        Optional[str], pydantic.Field(alias="clientSessionId")
    ] = None
    r"""Client provided sessionID to store events against."""

    streaming: Optional[bool] = False
    r"""Whether to stream the response instead of returning inline."""
