"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .executeprompt import ExecutePrompt, ExecutePromptTypedDict
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


EXECUTE_PROMPT_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud/core/aiservices/v4",
]


class ExecutePromptRequestTypedDict(TypedDict):
    prompt_id: str
    r"""ID of the prompt template from the AI console. Only published and active prompt IDs are allowed."""
    execute_prompt: NotRequired[ExecutePromptTypedDict]


class ExecutePromptRequest(BaseModel):
    prompt_id: Annotated[
        str,
        pydantic.Field(alias="promptId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the prompt template from the AI console. Only published and active prompt IDs are allowed."""

    execute_prompt: Annotated[
        Optional[ExecutePrompt],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
