"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptlanguage import AcceptLanguage
from .knowledgeexport import KnowledgeExport, KnowledgeExportTypedDict
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class ExportContentRequestTypedDict(TypedDict):
    accept_language: AcceptLanguage
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""
    knowledge_export: KnowledgeExportTypedDict


class ExportContentRequest(BaseModel):
    accept_language: Annotated[
        AcceptLanguage,
        pydantic.Field(alias="Accept-Language"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""

    knowledge_export: Annotated[
        KnowledgeExport,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ExportContentResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class ExportContentResponse(BaseModel):
    headers: Dict[str, List[str]]
