"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptlanguage import AcceptLanguage
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class ExportStatusRequestTypedDict(TypedDict):
    accept_language: AcceptLanguage
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""
    job_id: str
    r"""**Example Usage:**
    ```bash
    GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
    ```

    """


class ExportStatusRequest(BaseModel):
    accept_language: Annotated[
        AcceptLanguage,
        pydantic.Field(alias="Accept-Language"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""

    job_id: Annotated[
        str,
        pydantic.Field(alias="jobID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""**Example Usage:**
    ```bash
    GET /content/export/7A84B875-6F75-4C7B-B137-0632B62DB0BD/status
    ```

    """
