"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdby import CreatedBy, CreatedByTypedDict
from .modifiedby import ModifiedBy, ModifiedByTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VersionTypedDict(TypedDict):
    version_id: NotRequired[int]
    r"""ID of Hook File version"""
    is_current: NotRequired[bool]


class Version(BaseModel):
    version_id: Annotated[Optional[int], pydantic.Field(alias="versionID")] = None
    r"""ID of Hook File version"""

    is_current: Annotated[Optional[bool], pydantic.Field(alias="isCurrent")] = None


class FileTypedDict(TypedDict):
    name: str
    r"""Filename (e.g., script.js)."""
    content: str
    r"""Base64 encoded JavaScript content."""
    content_url: NotRequired[str]


class File(BaseModel):
    name: str
    r"""Filename (e.g., script.js)."""

    content: str
    r"""Base64 encoded JavaScript content."""

    content_url: Annotated[Optional[str], pydantic.Field(alias="contentUrl")] = None


class FileObjectTypedDict(TypedDict):
    file_id: NotRequired[str]
    r"""ID of Hook File"""
    created_date: NotRequired[str]
    r"""The date on which the resource was last modified."""
    created_by: NotRequired[CreatedByTypedDict]
    modified_date: NotRequired[str]
    r"""The date on which the resource was last modified."""
    modified_by: NotRequired[ModifiedByTypedDict]
    version: NotRequired[VersionTypedDict]
    file: NotRequired[FileTypedDict]


class FileObject(BaseModel):
    file_id: Annotated[Optional[str], pydantic.Field(alias="fileID")] = None
    r"""ID of Hook File"""

    created_date: Annotated[Optional[str], pydantic.Field(alias="createdDate")] = None
    r"""The date on which the resource was last modified."""

    created_by: Annotated[Optional[CreatedBy], pydantic.Field(alias="createdBy")] = None

    modified_date: Annotated[Optional[str], pydantic.Field(alias="modifiedDate")] = None
    r"""The date on which the resource was last modified."""

    modified_by: Annotated[Optional[ModifiedBy], pydantic.Field(alias="modifiedBy")] = (
        None
    )

    version: Optional[Version] = None

    file: Optional[File] = None
