"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptlanguage import AcceptLanguage
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, HeaderMetadata, QueryParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetAllArticleTypesRequestTypedDict(TypedDict):
    accept_language: AcceptLanguage
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""
    department_id: str
    r"""The ID of the department."""


class GetAllArticleTypesRequest(BaseModel):
    accept_language: Annotated[
        AcceptLanguage,
        pydantic.Field(alias="Accept-Language"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""

    department_id: Annotated[
        str,
        pydantic.Field(alias="departmentID"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The ID of the department."""
