"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptlanguage import AcceptLanguage
from egain_api_python.types import BaseModel
from egain_api_python.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


GET_PROMPT_TEMPLATE_BY_ID_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
]


GetPromptTemplateByIDLanguageCode = Literal[
    "en-US",
    "fr-FR",
    "en-GB",
    "es-ES",
    "it-IT",
    "nl-NL",
    "da-DA",
    "sv-SE",
    "pt-PT",
    "fi-FI",
    "no-NB",
    "no-NN",
    "ja-JA",
    "de-DE",
    "pt-BR",
    "zh-CN",
    "zh-TW",
    "ko-KO",
    "ru-RU",
    "el-EL",
    "tr-TR",
    "pl-PL",
    "cs-CS",
    "sk-SK",
    "hu-HU",
    "sr-SR",
    "ar-SA",
    "hr-HR",
    "ro-RO",
    "th-TH",
    "xx-XX",
]
r"""The language used while writing the prompt templates."""


class GetPromptTemplateByIDRequestTypedDict(TypedDict):
    accept_language: AcceptLanguage
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""
    department: str
    r"""Name of the department. Must be a valid department name."""
    language_code: GetPromptTemplateByIDLanguageCode
    r"""The language used while writing the prompt templates."""
    prompt_id: str
    r"""The promptID of the prompt template you want to fetch details for."""


class GetPromptTemplateByIDRequest(BaseModel):
    accept_language: Annotated[
        AcceptLanguage,
        pydantic.Field(alias="Accept-Language"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""

    department: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Name of the department. Must be a valid department name."""

    language_code: Annotated[
        GetPromptTemplateByIDLanguageCode,
        pydantic.Field(alias="languageCode"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The language used while writing the prompt templates."""

    prompt_id: Annotated[
        str,
        pydantic.Field(alias="promptID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The promptID of the prompt template you want to fetch details for."""
