"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .acceptlanguage import AcceptLanguage
from .prompttemplate import PromptTemplate, PromptTemplateTypedDict
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, HeaderMetadata, QueryParamMetadata
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_PROMPT_TEMPLATES_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
]


GetPromptTemplatesLanguageCode = Literal[
    "en-US",
    "fr-FR",
    "en-GB",
    "es-ES",
    "it-IT",
    "nl-NL",
    "da-DA",
    "sv-SE",
    "pt-PT",
    "fi-FI",
    "no-NB",
    "no-NN",
    "ja-JA",
    "de-DE",
    "pt-BR",
    "zh-CN",
    "zh-TW",
    "ko-KO",
    "ru-RU",
    "el-EL",
    "tr-TR",
    "pl-PL",
    "cs-CS",
    "sk-SK",
    "hu-HU",
    "sr-SR",
    "ar-SA",
    "hr-HR",
    "ro-RO",
    "th-TH",
    "xx-XX",
]
r"""The language used while writing the prompt templates."""


GetPromptTemplatesUseFor = Literal[
    "advisor",
    "knowledge",
    "custom",
]
r"""Filter prompt templates based on console."""


class GetPromptTemplatesRequestTypedDict(TypedDict):
    accept_language: AcceptLanguage
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""
    department: str
    r"""Name of the department. Must be a valid department name."""
    language_code: GetPromptTemplatesLanguageCode
    r"""The language used while writing the prompt templates."""
    name: NotRequired[str]
    r"""Fetch only templates with this exact name."""
    use_for: NotRequired[GetPromptTemplatesUseFor]
    r"""Filter prompt templates based on console."""


class GetPromptTemplatesRequest(BaseModel):
    accept_language: Annotated[
        AcceptLanguage,
        pydantic.Field(alias="Accept-Language"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The Language locale accepted by the client (used for locale specific fields in resource representation and in error responses)."""

    department: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Name of the department. Must be a valid department name."""

    language_code: Annotated[
        GetPromptTemplatesLanguageCode,
        pydantic.Field(alias="languageCode"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""The language used while writing the prompt templates."""

    name: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Fetch only templates with this exact name."""

    use_for: Annotated[
        Optional[GetPromptTemplatesUseFor],
        pydantic.Field(alias="useFor"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter prompt templates based on console."""


class GetPromptTemplatesResponseTypedDict(TypedDict):
    r"""Successful response with list of prompt templates"""

    prompt_templates: NotRequired[List[PromptTemplateTypedDict]]


class GetPromptTemplatesResponse(BaseModel):
    r"""Successful response with list of prompt templates"""

    prompt_templates: Annotated[
        Optional[List[PromptTemplate]], pydantic.Field(alias="promptTemplates")
    ] = None
