"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hooktypeparam import HookTypeParam
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GET_VALIDATION_HOOKS_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
]


class GetValidationHooksRequestTypedDict(TypedDict):
    type: NotRequired[HookTypeParam]
    r"""Filter by hook type."""


class GetValidationHooksRequest(BaseModel):
    type: Annotated[
        Optional[HookTypeParam],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by hook type."""
