"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
from egain_api_python.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


GET_VALIDATION_HOOK_VERSIONS_OP_SERVERS = [
    # Production Server
    "https://api.aidev.egain.cloud//knowledge/contentmgr/v4",
]


class GetValidationHookVersionsRequestTypedDict(TypedDict):
    hook_id: int
    r"""Integer ID of the Hook resource."""


class GetValidationHookVersionsRequest(BaseModel):
    hook_id: Annotated[
        int,
        pydantic.Field(alias="hookID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Integer ID of the Hook resource."""
