"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


HookTypeParam = Literal[
    "import_pre_validation_hook",
    "import_post_validation_hook",
]
