"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fileobject import FileObject, FileObjectTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


HookType = Literal[
    "import_pre_validation_hook",
    "import_post_validation_hook",
]


class HookTypedDict(TypedDict):
    type: HookType
    file_object: FileObjectTypedDict
    hook_id: NotRequired[int]
    r"""ID of hook"""
    name: NotRequired[str]
    r"""Name of the hook."""


class Hook(BaseModel):
    type: HookType

    file_object: Annotated[FileObject, pydantic.Field(alias="fileObject")]

    hook_id: Annotated[Optional[int], pydantic.Field(alias="hookID")] = None
    r"""ID of hook"""

    name: Optional[str] = None
    r"""Name of the hook."""
