"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hook import Hook, HookTypedDict
from egain_api_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class HooksTypedDict(TypedDict):
    hooks: NotRequired[List[HookTypedDict]]


class Hooks(BaseModel):
    hooks: Optional[List[Hook]] = None
