"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ImportStatusStatus = Literal[
    "Scheduled",
    "In Progress",
    "Successful",
    "Failed",
    "Cancelled",
]


class ImportStatusTypedDict(TypedDict):
    status: ImportStatusStatus
    log_file_location: NotRequired[str]


class ImportStatus(BaseModel):
    status: ImportStatusStatus

    log_file_location: Annotated[
        Optional[str], pydantic.Field(alias="logFileLocation")
    ] = None
