"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .s3config import S3Config, S3ConfigTypedDict
from .sftpconfig import SftpConfig, SftpConfigTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ArticleCategories = Literal[
    "searchable",
    "all",
]
r"""Category of articles to return. If all is selected, it includes both browsable and searchable articles."""


KnowledgeExportCode = Literal[
    "en-US",
    "fr-FR",
    "en-GB",
    "es-ES",
    "it-IT",
    "nl-NL",
    "da-DA",
    "sv-SE",
    "pt-PT",
    "fi-FI",
    "no-NB",
    "no-NN",
    "ja-JA",
    "de-DE",
    "pt-BR",
    "zh-CN",
    "zh-TW",
    "ko-KO",
    "ru-RU",
    "el-EL",
    "tr-TR",
    "pl-PL",
    "cs-CS",
    "sk-SK",
    "hu-HU",
    "sr-SR",
    "ar-SA",
    "hr-HR",
    "ro-RO",
    "th-TH",
    "de-AT",
    "vi-VN",
    "id-ID",
    "ms-MY",
    "fil-PH",
    "fr-CA",
    "hi-IN",
    "uk-UA",
    "bg-BG",
    "sl-SI",
    "xx-XX",
]
r"""The code of the language."""


class KnowledgeExportLanguageTypedDict(TypedDict):
    r"""The Knowledge Base language in which the content is created."""

    code: KnowledgeExportCode
    r"""The code of the language."""


class KnowledgeExportLanguage(BaseModel):
    r"""The Knowledge Base language in which the content is created."""

    code: KnowledgeExportCode
    r"""The code of the language."""


ResourceType = Literal[
    "articles",
    "topics",
    "portals",
    "all",
]


DestinationType = Literal[
    "AWS S3 bucket",
    "SFTP server",
]
r"""Type of data destination"""


class DataDestinationTypedDict(TypedDict):
    destination_type: DestinationType
    r"""Type of data destination"""
    path: str
    r"""Path of the data destination. For S3 bucket, it can be root or a folder. For SFTP, it can be target directory on the server.

    **Examples:**

    * **For S3:** `\"s3://amzn-s3-demo-bucket/mydeptfolder\"`
    * **For SFTP:** `\"exports/mydeptfolder\"`

    """
    sftp_details: NotRequired[SftpConfigTypedDict]
    s3_details: NotRequired[S3ConfigTypedDict]


class DataDestination(BaseModel):
    destination_type: Annotated[
        DestinationType, pydantic.Field(alias="destinationType")
    ]
    r"""Type of data destination"""

    path: str
    r"""Path of the data destination. For S3 bucket, it can be root or a folder. For SFTP, it can be target directory on the server.

    **Examples:**

    * **For S3:** `\"s3://amzn-s3-demo-bucket/mydeptfolder\"`
    * **For SFTP:** `\"exports/mydeptfolder\"`

    """

    sftp_details: Annotated[
        Optional[SftpConfig], pydantic.Field(alias="sftpDetails")
    ] = None

    s3_details: Annotated[Optional[S3Config], pydantic.Field(alias="s3Details")] = None


class KnowledgeExportTypedDict(TypedDict):
    portal_id: str
    r"""The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits."""
    language: KnowledgeExportLanguageTypedDict
    r"""The Knowledge Base language in which the content is created."""
    resource_types: List[ResourceType]
    r"""Types of Knowledge Hub resources to export. Use 'all' to specify all resource types at once.

    Below are the attributes that are returned for each resource type specified.

    ##### Portal Resource Type Attributes
    Portal Attribute Name | Description
    ------------------------------- | -----------
    | id | The ID of the Portal in Readable format.
    | alternateId | The system-generated ID of the Portal in long format.
    | name  | The name of the Portal.
    | description | The Portal's description.
    | departmentId | ID of the department this Portal belongs to.
    | defaultContentLanguageId | The default ID of the language for the portal content.

    ##### Topic Resource Type Attributes
    | Topic Attribute Name | Description
    | ------------------------------ | -----------
    | id | The ID of the Topic in Readable form.
    | alternateId | The system-generated ID of the Topic in long form.
    | name  | The name of the Topic.
    | departmentId | ID of the department this Topic belongs to.
    | modifiedDate | The date when the Topic was last modified on.
    | topicHomeArticleId | The ID of the Article used as the home page of this Topic.
    | childCount | Total number of children sub-topis below the current Topic.
    | subTopicIds | Array with the list of sub-topics (all levels of the topic hierarchy).
    | parentTopicId | ID of the parent Topic. -1 if it is the root Topic.
    | imageURL | URL of the inline Topic image.
    | customAttributes | One or more comma-separated names for Topic custom attributes defined by the user to be returned.

    ##### Article Resource Type Attributes
    Export article's attributes returned are aligned with the response of the [Get Article By ID with Editions](../article/getarticlebyidwitheditions) API.

    """
    data_destination: DataDestinationTypedDict
    article_categories: NotRequired[ArticleCategories]
    r"""Category of articles to return. If all is selected, it includes both browsable and searchable articles."""
    export_unpublished_only: NotRequired[bool]
    r"""Determines which article version to export. If true, the latest unpublished version will be exported for each article where available, and articles that do not have an unpublished version will be omitted from the export. If this property is false or omitted, the latest published version will be exported for each article where available. Each request exports either all published or all unpublished article versions in a portal; never both."""


class KnowledgeExport(BaseModel):
    portal_id: Annotated[str, pydantic.Field(alias="portalID")]
    r"""The ID of the portal being accessed.<br><br>A portal ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits."""

    language: KnowledgeExportLanguage
    r"""The Knowledge Base language in which the content is created."""

    resource_types: Annotated[List[ResourceType], pydantic.Field(alias="resourceTypes")]
    r"""Types of Knowledge Hub resources to export. Use 'all' to specify all resource types at once.

    Below are the attributes that are returned for each resource type specified.

    ##### Portal Resource Type Attributes
    Portal Attribute Name | Description
    ------------------------------- | -----------
    | id | The ID of the Portal in Readable format.
    | alternateId | The system-generated ID of the Portal in long format.
    | name  | The name of the Portal.
    | description | The Portal's description.
    | departmentId | ID of the department this Portal belongs to.
    | defaultContentLanguageId | The default ID of the language for the portal content.

    ##### Topic Resource Type Attributes
    | Topic Attribute Name | Description
    | ------------------------------ | -----------
    | id | The ID of the Topic in Readable form.
    | alternateId | The system-generated ID of the Topic in long form.
    | name  | The name of the Topic.
    | departmentId | ID of the department this Topic belongs to.
    | modifiedDate | The date when the Topic was last modified on.
    | topicHomeArticleId | The ID of the Article used as the home page of this Topic.
    | childCount | Total number of children sub-topis below the current Topic.
    | subTopicIds | Array with the list of sub-topics (all levels of the topic hierarchy).
    | parentTopicId | ID of the parent Topic. -1 if it is the root Topic.
    | imageURL | URL of the inline Topic image.
    | customAttributes | One or more comma-separated names for Topic custom attributes defined by the user to be returned.

    ##### Article Resource Type Attributes
    Export article's attributes returned are aligned with the response of the [Get Article By ID with Editions](../article/getarticlebyidwitheditions) API.

    """

    data_destination: Annotated[
        DataDestination, pydantic.Field(alias="dataDestination")
    ]

    article_categories: Annotated[
        Optional[ArticleCategories], pydantic.Field(alias="articleCategories")
    ] = "searchable"
    r"""Category of articles to return. If all is selected, it includes both browsable and searchable articles."""

    export_unpublished_only: Annotated[
        Optional[bool], pydantic.Field(alias="exportUnpublishedOnly")
    ] = False
    r"""Determines which article version to export. If true, the latest unpublished version will be exported for each article where available, and articles that do not have an unpublished version will be omitted from the export. If this property is false or omitted, the latest published version will be exported for each article where available. Each request exports either all published or all unpublished article versions in a portal; never both."""
