"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createdby import CreatedBy, CreatedByTypedDict
from datetime import datetime
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


UseFor = Literal[
    "knowledge",
    "advisor",
    "custom",
]
r"""Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console)."""


AppliesTo = Literal[
    "article",
    "chat",
    "email",
]
r"""The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used."""


OutputFormat = Literal[
    "html",
    "text",
]
r"""The output format for the generated output."""


ReviewStatus = Literal["published",]
r"""Review status of the prompt."""


DisplayAt = Literal[
    "article.content-area",
    "article.metadata",
]


class PromptTemplateTypedDict(TypedDict):
    name: str
    r"""Name of the prompt template"""
    id: str
    r"""ID of the prompt template from the AI console"""
    description: str
    active: bool
    r"""A boolean showing whether a prompt is active or inactive."""
    use_for: UseFor
    r"""Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console)."""
    applies_to: AppliesTo
    r"""The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used."""
    instruction: str
    r"""The prompt instructions."""
    output_format: OutputFormat
    r"""The output format for the generated output."""
    created_on: datetime
    r"""Date and time when the prompt template was created."""
    modified_date: datetime
    r"""Date and time when the prompt was last updated."""
    created_by: CreatedByTypedDict
    review_status: ReviewStatus
    r"""Review status of the prompt."""
    is_system_created: bool
    r"""A boolean showing whether the prompt template came out of the box or is a custom prompt."""
    field_to_update: str
    r"""This will return the specified field to update once a user inserts the generated content. This value can be one of the following:

    - title
    - content
    - keyword
    - description
    - summary
    - replyarea
    - notes
    - subject
    - classification

    It can also return a custom attribute which will follow the following convention:

    `custom.<attributeType>.<customAttributeName>`

    """
    display_at: NotRequired[List[DisplayAt]]


class PromptTemplate(BaseModel):
    name: str
    r"""Name of the prompt template"""

    id: str
    r"""ID of the prompt template from the AI console"""

    description: str

    active: bool
    r"""A boolean showing whether a prompt is active or inactive."""

    use_for: Annotated[UseFor, pydantic.Field(alias="useFor")]
    r"""Specifies which console the prompt applies to: 'knowledge', 'advisor', or 'custom' (for prompts used outside any console)."""

    applies_to: Annotated[AppliesTo, pydantic.Field(alias="appliesTo")]
    r"""The 'channel' for this prompt. If the `useFor` is set to 'knowledge' then article is used. If `useFor` is set to 'advisor', then either 'chat' or 'email' can be used."""

    instruction: str
    r"""The prompt instructions."""

    output_format: Annotated[OutputFormat, pydantic.Field(alias="outputFormat")]
    r"""The output format for the generated output."""

    created_on: Annotated[datetime, pydantic.Field(alias="createdOn")]
    r"""Date and time when the prompt template was created."""

    modified_date: Annotated[datetime, pydantic.Field(alias="modifiedDate")]
    r"""Date and time when the prompt was last updated."""

    created_by: Annotated[CreatedBy, pydantic.Field(alias="createdBy")]

    review_status: Annotated[ReviewStatus, pydantic.Field(alias="reviewStatus")]
    r"""Review status of the prompt."""

    is_system_created: Annotated[bool, pydantic.Field(alias="isSystemCreated")]
    r"""A boolean showing whether the prompt template came out of the box or is a custom prompt."""

    field_to_update: Annotated[str, pydantic.Field(alias="fieldToUpdate")]
    r"""This will return the specified field to update once a user inserts the generated content. This value can be one of the following:

    - title
    - content
    - keyword
    - description
    - summary
    - replyarea
    - notes
    - subject
    - classification

    It can also return a custom attribute which will follow the following convention:

    `custom.<attributeType>.<customAttributeName>`

    """

    display_at: Annotated[
        Optional[List[DisplayAt]], pydantic.Field(alias="displayAt")
    ] = None
