"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchreplacement import SearchReplacement, SearchReplacementTypedDict
from .staticreplacement import StaticReplacement, StaticReplacementTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ReplacementTypedDict = TypeAliasType(
    "ReplacementTypedDict",
    Union[StaticReplacementTypedDict, SearchReplacementTypedDict],
)


Replacement = TypeAliasType("Replacement", Union[StaticReplacement, SearchReplacement])
