"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class S3ConfigTypedDict(TypedDict):
    region: str
    r"""Region of the data destination"""
    access_key: str
    secret_key: str


class S3Config(BaseModel):
    region: str
    r"""Region of the data destination"""

    access_key: Annotated[str, pydantic.Field(alias="accessKey")]

    secret_key: Annotated[str, pydantic.Field(alias="secretKey")]
