"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


SearchReplacementType = Literal["search",]
r"""Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template."""


class SearchReplacementTypedDict(TypedDict):
    type: SearchReplacementType
    r"""Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template."""
    name: str
    r"""The placeholder variable in the prompt template that will be replaced with search results."""
    portal_id: str
    r"""The portal identifier where the search will be performed."""
    q: str
    r"""The search query string to run against the specified portal."""


class SearchReplacement(BaseModel):
    type: SearchReplacementType
    r"""Identifies this replacement as a **search result**. At execution, results from a portal search will replace the variable `name` in the prompt template."""

    name: str
    r"""The placeholder variable in the prompt template that will be replaced with search results."""

    portal_id: Annotated[str, pydantic.Field(alias="portalId")]
    r"""The portal identifier where the search will be performed."""

    q: str
    r"""The search query string to run against the specified portal."""
