"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .aitopicbreadcrumb import AITopicBreadcrumb, AITopicBreadcrumbTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


SearchResultDocType = Literal[
    "HTML",
    "DOCX",
    "PDF",
    "PPTX",
]
r"""Format of the source document (HTML, DOCX, PPTX, or PDF)."""


SearchResultSource = Literal[
    "eGain Article",
    "eGain Attachment",
]
r"""The repository or system where the content originated (e.g., eGain Article, eGain Attachment)."""


SnippetType = Literal[
    "chunks",
    "articleContent",
]


class SearchResultTypedDict(TypedDict):
    r"""Represents a single document or snippet returned by search, along with its metadata and relevance score."""

    id: str
    r"""The ID of the Article. <br><br> An Article ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits."""
    name: str
    r"""The name of the Article or source content."""
    doc_type: SearchResultDocType
    r"""Format of the source document (HTML, DOCX, PPTX, or PDF)."""
    source: SearchResultSource
    r"""The repository or system where the content originated (e.g., eGain Article, eGain Attachment)."""
    snippet: str
    r"""Retrieved text returned for the query. This may be a **chunk of an article** or the **entire article content** if the content is small enough."""
    normalized_score: float
    r"""Relative ranking score (0.0-1.0) normalized across all returned results, based on a combination of BM25 and semantic similarity scores. This score indicates how a result ranks compared to others in the same response, not its absolute relevance to the query. As a result, a high score does not necessarily imply strong query relevance.

    """
    doc_name: NotRequired[str]
    r"""Name of the attachment, if an attachment was used as the source content."""
    contextual_summary: NotRequired[str]
    r"""Contextual Summary generated as part of metadata for the chunk content."""
    snippet_type: NotRequired[SnippetType]
    relevance_score: NotRequired[float]
    r"""Query-specific relevance score (0.0-1.0) that reflects how well the result matches the user query. This score is only available when a re-ranker is enabled and represents a direct relevance comparison between the query and the returned snippet.

    """
    topic_breadcrumb: NotRequired[List[AITopicBreadcrumbTypedDict]]


class SearchResult(BaseModel):
    r"""Represents a single document or snippet returned by search, along with its metadata and relevance score."""

    id: str
    r"""The ID of the Article. <br><br> An Article ID is composed of a 2-4 letter prefix, followed by a dash and 4-15 digits."""

    name: str
    r"""The name of the Article or source content."""

    doc_type: Annotated[SearchResultDocType, pydantic.Field(alias="docType")]
    r"""Format of the source document (HTML, DOCX, PPTX, or PDF)."""

    source: SearchResultSource
    r"""The repository or system where the content originated (e.g., eGain Article, eGain Attachment)."""

    snippet: str
    r"""Retrieved text returned for the query. This may be a **chunk of an article** or the **entire article content** if the content is small enough."""

    normalized_score: Annotated[float, pydantic.Field(alias="normalizedScore")]
    r"""Relative ranking score (0.0-1.0) normalized across all returned results, based on a combination of BM25 and semantic similarity scores. This score indicates how a result ranks compared to others in the same response, not its absolute relevance to the query. As a result, a high score does not necessarily imply strong query relevance.

    """

    doc_name: Annotated[Optional[str], pydantic.Field(alias="docName")] = None
    r"""Name of the attachment, if an attachment was used as the source content."""

    contextual_summary: Annotated[
        Optional[str], pydantic.Field(alias="contextualSummary")
    ] = None
    r"""Contextual Summary generated as part of metadata for the chunk content."""

    snippet_type: Annotated[
        Optional[SnippetType], pydantic.Field(alias="snippetType")
    ] = None

    relevance_score: Annotated[
        Optional[float], pydantic.Field(alias="relevanceScore")
    ] = None
    r"""Query-specific relevance score (0.0-1.0) that reflects how well the result matches the user query. This score is only available when a re-ranker is enabled and represents a direct relevance comparison between the query and the returned snippet.

    """

    topic_breadcrumb: Annotated[
        Optional[List[AITopicBreadcrumb]], pydantic.Field(alias="topicBreadcrumb")
    ] = None
