"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SftpConfigTypedDict(TypedDict):
    username: str
    host: str
    r"""The hostname of the SFTP server"""
    password: NotRequired[str]
    port: NotRequired[int]
    r"""The server port number"""


class SftpConfig(BaseModel):
    username: str

    host: str
    r"""The hostname of the SFTP server"""

    password: Optional[str] = None

    port: Optional[int] = 22
    r"""The server port number"""
