"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from egain_api_python.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


StaticReplacementType = Literal["static",]
r"""Identifies this replacement as a **static value**. At execution, the specified `value` will replace the variable `name` in the prompt template."""


class StaticReplacementTypedDict(TypedDict):
    type: StaticReplacementType
    r"""Identifies this replacement as a **static value**. At execution, the specified `value` will replace the variable `name` in the prompt template."""
    name: str
    r"""The placeholder variable in the prompt template that will be replaced."""
    value: str
    r"""The literal value to insert into the prompt when executed."""


class StaticReplacement(BaseModel):
    type: StaticReplacementType
    r"""Identifies this replacement as a **static value**. At execution, the specified `value` will replace the variable `name` in the prompt template."""

    name: str
    r"""The placeholder variable in the prompt template that will be replaced."""

    value: str
    r"""The literal value to insert into the prompt when executed."""
