"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .topicbreadcrumb import TopicBreadcrumb, TopicBreadcrumbTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TopicBreadcrumbsListTypedDict(TypedDict):
    r"""This schema contains an array of topic breadcrumbs, allowing clients to distinguish between multiple distinct hierarchical topic paths."""

    topic_breadcrumb: NotRequired[List[TopicBreadcrumbTypedDict]]
    r"""An array of TopicBreadcrumb instances representing individual paths."""


class TopicBreadcrumbsList(BaseModel):
    r"""This schema contains an array of topic breadcrumbs, allowing clients to distinguish between multiple distinct hierarchical topic paths."""

    topic_breadcrumb: Annotated[
        Optional[List[TopicBreadcrumb]], pydantic.Field(alias="topicBreadcrumb")
    ] = None
    r"""An array of TopicBreadcrumb instances representing individual paths."""
