"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasourcecredentials import DataSourceCredentials, DataSourceCredentialsTypedDict
from egain_api_python.types import BaseModel
import pydantic
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ValidateImportContentType = Literal[
    "AWS S3 bucket",
    "Shared file path",
]
r"""Type of data source"""


class ValidateImportContentDataSourceTypedDict(TypedDict):
    type: ValidateImportContentType
    r"""Type of data source"""
    path: str
    r"""Path of the data source"""
    region: NotRequired[str]
    r"""Region of the data source"""
    credentials: NotRequired[DataSourceCredentialsTypedDict]


class ValidateImportContentDataSource(BaseModel):
    type: ValidateImportContentType
    r"""Type of data source"""

    path: str
    r"""Path of the data source"""

    region: Optional[str] = None
    r"""Region of the data source"""

    credentials: Optional[DataSourceCredentials] = None


class ValidateImportContentTypedDict(TypedDict):
    data_source: ValidateImportContentDataSourceTypedDict


class ValidateImportContent(BaseModel):
    data_source: Annotated[
        ValidateImportContentDataSource, pydantic.Field(alias="dataSource")
    ]
