"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from egain_api_python import errors, models, utils
from egain_api_python._hooks import HookContext
from egain_api_python.types import OptionalNullable, UNSET
from egain_api_python.utils import get_security_from_env
from egain_api_python.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, List, Mapping, Optional, Union


class AiservicesPrompt(BaseSDK):
    def execute_prompt(
        self,
        *,
        prompt_id: str,
        department: str,
        language_code: models.LanguageCodeRequestBody,
        replacements: Optional[
            Union[List[models.Replacement], List[models.ReplacementTypedDict]]
        ] = None,
        event_type: Optional[models.EventTypeRequestBody] = "generate",
        client_session_id: Optional[str] = None,
        streaming: Optional[bool] = False,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ExecutePromptResponse:
        r"""Execute a predefined prompt

        Execute a published and active prompt template from the AI console.

        :param prompt_id: ID of the prompt template from the AI console. Only published and active prompt IDs are allowed.
        :param department: Name of the department. Must be a valid department name.
        :param language_code: The language used for the prompt template.
        :param replacements: List of variable replacements (either static or search).
        :param event_type: Event type logged when the API executes successfully.
        :param client_session_id: Client provided sessionID to store events against.
        :param streaming: Whether to stream the response instead of returning inline.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.EXECUTE_PROMPT_OP_SERVERS[0]

        request = models.ExecutePromptRequest(
            prompt_id=prompt_id,
            execute_prompt=models.ExecutePrompt(
                department=department,
                language_code=language_code,
                replacements=utils.get_pydantic_model(
                    replacements, Optional[List[models.Replacement]]
                ),
                event_type=event_type,
                client_session_id=client_session_id,
                streaming=streaming,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/promptmanager/execute/prompt/{promptId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.execute_prompt,
                False,
                True,
                "json",
                Optional[models.ExecutePrompt],
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="executePrompt",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=[
                "400",
                "401",
                "403",
                "404",
                "429",
                "4XX",
                "500",
                "503",
                "5XX",
            ],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ExecutePromptResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.BadRequestErrorData, http_res
            )
            raise errors.BadRequestError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "404", "429", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.EgainDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.EgainDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.EgainDefaultError("Unexpected response received", http_res)

    async def execute_prompt_async(
        self,
        *,
        prompt_id: str,
        department: str,
        language_code: models.LanguageCodeRequestBody,
        replacements: Optional[
            Union[List[models.Replacement], List[models.ReplacementTypedDict]]
        ] = None,
        event_type: Optional[models.EventTypeRequestBody] = "generate",
        client_session_id: Optional[str] = None,
        streaming: Optional[bool] = False,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ExecutePromptResponse:
        r"""Execute a predefined prompt

        Execute a published and active prompt template from the AI console.

        :param prompt_id: ID of the prompt template from the AI console. Only published and active prompt IDs are allowed.
        :param department: Name of the department. Must be a valid department name.
        :param language_code: The language used for the prompt template.
        :param replacements: List of variable replacements (either static or search).
        :param event_type: Event type logged when the API executes successfully.
        :param client_session_id: Client provided sessionID to store events against.
        :param streaming: Whether to stream the response instead of returning inline.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.EXECUTE_PROMPT_OP_SERVERS[0]

        request = models.ExecutePromptRequest(
            prompt_id=prompt_id,
            execute_prompt=models.ExecutePrompt(
                department=department,
                language_code=language_code,
                replacements=utils.get_pydantic_model(
                    replacements, Optional[List[models.Replacement]]
                ),
                event_type=event_type,
                client_session_id=client_session_id,
                streaming=streaming,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/promptmanager/execute/prompt/{promptId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.execute_prompt,
                False,
                True,
                "json",
                Optional[models.ExecutePrompt],
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="executePrompt",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=[
                "400",
                "401",
                "403",
                "404",
                "429",
                "4XX",
                "500",
                "503",
                "5XX",
            ],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ExecutePromptResponse, http_res)
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.BadRequestErrorData, http_res
            )
            raise errors.BadRequestError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "404", "429", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.EgainDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.EgainDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.EgainDefaultError("Unexpected response received", http_res)
